version: '3'
services:
  web:
    image: orlea/mastodon:3.2.1-MOD
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    networks:
      - private
    restart: always
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "hogehoge"
        awslogs-stream: "web"
  streaming:
    image: orlea/mastodon:3.2.1-MOD
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    env_file: .env.production
    command: node ./streaming
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    networks:
      - private
    restart: always
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "hogehoge"
        awslogs-stream: "sidekiq"
  sidekiq:
    image: orlea/mastodon:3.2.1-MOD
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    env_file: .env.production
    command: bundle exec sidekiq -c 10
    networks:
      - private
    restart: always
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "hogehoge"
        awslogs-stream: "streaming"

networks:
  private:
    external: true
