version: '3'
services:
  web:
    image: tootsuite/mastodon:v3.1.4
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    networks:
      - private
  streaming:
    image: tootsuite/mastodon:v3.1.4
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    env_file: .env.production
    command: node ./streaming
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    networks:
      - private
  sidekiq:
    image: tootsuite/mastodon:v3.1.4
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    env_file: .env.production
    command: bundle exec sidekiq -c 10
    networks:
      - private

networks:
  private:
